export const vocabulary = [
  {name: 'Alphabet'},
  {name: 'Greetings and politeness'},
  {name: 'Numbers from 1 to 20'},
  {name: 'Colors'},
  {name: 'Days of the week'},
  {name: 'Months'},
  {name: 'Food'},
  {name: 'Animals'},
  {name: 'Family members'},
  {name: 'Weather'},
  {name: 'Countries'},
  {name: 'Cities'},
  {name: 'Transportation'},
  {name: 'Clothes'},
  {name: 'School subjects'},
  {name: 'Furniture'},
  {name: 'Professions'},
  {name: 'Hobbies'},
  {name: 'Sports'},
  {name: 'Nature'},
  {name: 'Body parts'},
  {name: 'Health'},
  {name: 'Feelings'},
  {name: 'Time'},
  {name: 'Technology'},
  {name: 'Travel'},
  {name: 'Shopping'},
  {name: 'Music'},
  {name: 'Movies'},
  {name: 'Literature'},
  {name: 'Art'},
  {name: 'History'},
  {name: 'Geography'},
  {name: 'Science'},
  {name: 'Chemistry'},
  {name: 'Physics'},
  {name: 'Math'},
  {name: 'Economics'},
  {name: 'Politics'},
  {name: 'Religion'},
  {name: 'Books'},
  {name: 'Entertainment'},
  {name: 'Social media'},
  {name: 'Communication'},
  {name: 'Business'},
  {name: 'Banking'},
  {name: 'Law'},
  {name: 'Government'},
  {name: 'Environment'},
  {name: 'Pollution'},
  {name: 'Climate change'},
  {name: 'Recycling'},
  {name: 'Waste management'},
  {name: 'Technology gadgets'},
  {name: 'Phones'},
  {name: 'Computers'},
  {name: 'Tablets'},
  {name: 'Television'},
  {name: 'Games'},
  {name: 'Vehicles'},
  {name: 'Airplanes'},
  {name: 'Boats'},
  {name: 'Bicycles'},
  {name: 'Trains'},
  {name: 'Cars'},
  {name: 'Motorcycles'},
  {name: 'Buses'},
  {name: 'Luggage'},
  {name: 'Hotels'},
  {name: 'Restaurants'},
  {name: 'Tourism'},
  {name: 'Landmarks'},
  {name: 'Shopping centers'},
  {name: 'Markets'},
  {name: 'Grocery store'},
  {name: 'Supermarket'},
  {name: 'Discount'},
  {name: 'Sale'},
  {name: 'Price'},
  {name: 'Money'},
  {name: 'Bank'},
  {name: 'Account'},
  {name: 'Debit card'},
  {name: 'Credit card'},
  {name: 'Investment'},
  {name: 'Stocks'},
  {name: 'Bonds'},
  {name: 'Loans'},
  {name: 'Debt'},
  {name: 'Insurance'},
  {name: 'Mortgage'},
  {name: 'Real estate'},
  {name: 'Renting'},
  {name: 'Buying'},
  {name: 'Selling'},
  {name: 'Contract'},
  {name: 'Offer'},
  {name: 'Transaction'},
  {name: 'Customer'},
  {name: 'Business owner'},
  {name: 'Employee'},
  {name: 'Employer'},
  {name: 'Office'},
  {name: 'Meeting'},
  {name: 'Presentation'},
  {name: 'Negotiation'},
  {name: 'Salary'},
  {name: 'Tax'},
  {name: 'Workplace'},
];

export const sentences = [
  {name: 'Hello, how are you?'},
  {name: 'I am fine, thank you!'},
  {name: 'What is your name?'},
  {name: 'My name is John.'},
  {name: 'Where do you live?'},
  {name: 'I live in New York.'},
  {name: 'How old are you?'},
  {name: 'I am 25 years old.'},
  {name: 'What time is it?'},
  {name: 'It’s 3 o’clock.'},
  {name: 'Can you help me?'},
  {name: 'Yes, of course!'},
  {name: 'Please, sit down.'},
  {name: 'Thank you very much.'},
  {name: 'You are welcome.'},
  {name: 'I need a taxi.'},
  {name: 'Where is the nearest hospital?'},
  {name: 'I am lost.'},
  {name: 'Can I get a ticket to the museum?'},
  {name: 'How much is this?'},
  {name: 'It’s $20.'},
  {name: 'What is your favorite color?'},
  {name: 'My favorite color is blue.'},
  {name: 'Where are you from?'},
  {name: 'I am from France.'},
  {name: 'What is the weather like today?'},
  {name: 'It’s sunny and warm.'},
  {name: 'I would like to order food.'},
  {name: 'Can I get a coffee?'},
  {name: 'How do I get to the airport?'},
  {name: 'Take the bus to the left.'},
  {name: 'Do you speak English?'},
  {name: 'Yes, I do.'},
  {name: 'No, I don’t.'},
  {name: 'Excuse me, can I ask you a question?'},
  {name: 'What time does the train leave?'},
  {name: 'The train leaves at 5 PM.'},
  {name: 'Is this your first time in the city?'},
  {name: 'Yes, it is.'},
  {name: 'No, I have been here before.'},
  {name: 'What’s the problem?'},
  {name: 'I lost my wallet.'},
  {name: 'I’m looking for the library.'},
  {name: 'The library is on Main Street.'},
  {name: 'How far is the nearest store?'},
  {name: 'It’s just around the corner.'},
  {name: 'Could you show me the way?'},
  {name: 'Of course, follow me.'},
  {name: 'Is it far from here?'},
  {name: 'No, it’s just a few blocks away.'},
  {name: 'Are you free tomorrow?'},
  {name: 'Yes, I’m free.'},
  {name: 'What are you doing today?'},
  {name: 'I am going to the gym.'},
  {name: 'I’m sorry for being late.'},
  {name: 'No problem.'},
  {name: 'Can you repeat that, please?'},
  {name: 'Sure, I will repeat it.'},
  {name: 'Are you hungry?'},
  {name: 'Yes, I am.'},
  {name: 'No, I’m not hungry.'},
  {name: 'What are you going to do this weekend?'},
  {name: 'I am going to visit my family.'},
  {name: 'I am planning to relax at home.'},
  {name: 'Do you like to read books?'},
  {name: 'Yes, I love reading.'},
  {name: 'What kind of music do you like?'},
  {name: 'I like pop music.'},
  {name: 'Do you play sports?'},
  {name: 'Yes, I play basketball.'},
  {name: 'No, I don’t play any sports.'},
  {name: 'What’s your favorite movie?'},
  {name: 'My favorite movie is The Matrix.'},
  {name: 'How many languages do you speak?'},
  {name: 'I speak three languages.'},
  {name: 'Can you give me directions to the park?'},
  {name: 'Sure, go straight and take a left.'},
  {name: 'Where can I buy a SIM card?'},
  {name: 'You can buy one at the airport.'},
  {name: 'What’s your job?'},
  {name: 'I am a teacher.'},
  {name: 'What’s your hobby?'},
  {name: 'I like painting.'},
  {name: 'Can I have the bill, please?'},
  {name: 'Of course, here it is.'},
  {name: 'I’m feeling tired.'},
  {name: 'You should take a break.'},
  {name: 'What do you want to eat?'},
  {name: 'I want pizza.'},
  {name: 'Can we meet tomorrow?'},
  {name: 'Yes, let’s meet at 2 PM.'},
  {name: 'I am excited about the trip.'},
  {name: 'Me too, I can’t wait!'},
];

export const dialogues = [
  {
    name:
      'A: Hi! How are you?\nB: I’m good, thanks! How about you?\nA: I’m doing great, thank you for asking!',
  },
  {
    name:
      'A: Where are you from?\nB: I’m from Italy.\nA: Oh, I’ve always wanted to visit Italy! What part are you from?\nB: I’m from Rome.',
  },
  {
    name:
      'A: Can I help you with anything?\nB: Yes, I’m looking for a new phone.\nA: What kind of phone are you looking for?\nB: I want something with a good camera.',
  },
  {
    name:
      'A: What time is the meeting?\nB: It’s at 2 PM.\nA: Thank you for letting me know!',
  },
  {
    name:
      'A: Do you want to go to the cinema tonight?\nB: Sure! What movie should we watch?\nA: How about the new action movie?\nB: Sounds good!',
  },
  {
    name:
      'A: I’m feeling hungry.\nB: Let’s grab some food.\nA: What do you want to eat?\nB: How about some sushi?\nA: Great idea!',
  },
  {
    name:
      'A: Do you like coffee?\nB: Yes, I love it! How about you?\nA: Me too, let’s grab a cup together sometime.\nB: Sounds great!',
  },
  {
    name:
      'A: Where is the nearest bus stop?\nB: It’s just down the street, next to the grocery store.\nA: Thanks for the information!',
  },
  {
    name:
      'A: How’s the weather today?\nB: It’s sunny and warm.\nA: Perfect weather for a walk in the park!',
  },
  {
    name:
      'A: Do you need help?\nB: Yes, could you please tell me where the restroom is?\nA: Sure, it’s on the right side of the hall.',
  },
  {
    name:
      'A: I’m looking for a gift for my friend.\nB: What does your friend like?\nA: She loves art.\nB: How about a painting set?',
  },
];

export const grammar = [
  {name: 'Present Simple Tense (I eat, you work)'},
  {name: 'Present Continuous Tense (I am eating, you are working)'},
  {name: 'Past Simple Tense (I ate, you worked)'},
  {name: 'Past Continuous Tense (I was eating, you were working)'},
  {name: 'Future Simple Tense (I will eat, you will work)'},
  {name: 'Future Continuous Tense (I will be eating, you will be working)'},
  {name: 'Present Perfect Tense (I have eaten, you have worked)'},
  {name: 'Past Perfect Tense (I had eaten, you had worked)'},
  {name: 'Future Perfect Tense (I will have eaten, you will have worked)'},
  {name: 'Comparatives (bigger, smaller)'},
  {name: 'Superlatives (biggest, smallest)'},
  {name: 'Countable and Uncountable Nouns'},
  {name: 'Articles (a, an, the)'},
  {name: 'Prepositions of place (in, on, at)'},
  {name: 'Prepositions of time (in, on, at)'},
  {name: 'Subject Pronouns (I, you, he, she)'},
  {name: 'Object Pronouns (me, you, him, her)'},
  {name: 'Possessive Pronouns (my, your, his, her)'},
  {name: 'Adverbs of Frequency (always, usually, often)'},
  {name: 'Adverbs of Manner (quickly, slowly)'},
  {name: 'Adjectives (big, small, beautiful)'},
  {name: 'Determiners (this, that, these, those)'},
  {name: 'Conjunctions (and, but, because)'},
  {name: 'Conditional Sentences (If I go, I will be happy)'},
  {name: 'Relative Clauses (who, which, that)'},
  {name: 'Direct and Indirect Speech'},
  {name: 'Modal Verbs (can, should, must)'},
  {name: 'Imperatives (Eat it! Go there!)'},
  {name: 'Questions (What, Where, Why, How)'},
  {name: 'Quantifiers (some, many, few, much)'},
  {name: 'Gerunds and Infinitives (I like swimming, I want to swim)'},
  {name: 'Phrasal Verbs (get up, look for, take off)'},
  {
    name:
      'Past Perfect Continuous Tense (I had been eating, you had been working)',
  },
  {
    name:
      'Future Perfect Continuous Tense (I will have been eating, you will have been working)',
  },
  {name: 'Exclamations (What a beautiful day!)'},
  {name: 'Reported Speech (He said that he was tired)'},
  {name: 'Future Time Clauses (when, before, after)'},
  {name: 'Tag Questions (You’re coming, aren’t you?)'},
  {name: 'Subjunctive Mood (If I were you, I would...)'},
  {name: 'Double Negatives (I don’t know nothing)'},
  {name: 'Ellipsis (I’m going to the store, and you?)'},
  {name: 'Synonyms and Antonyms'},
  {name: 'Active and Passive Voice'},
  {name: 'Causative Verbs (have, get)'},
  {name: 'Future-in-the-Past (He said he would call me)'},
  {name: 'Inversion (Never have I seen such beauty)'},
  {name: 'Emphasizing with Do (I do like it!)'},
  {name: 'Forming Questions with Do/Does/Did'},
  {name: 'Comparing with as...as (She is as tall as me)'},
  {name: 'Comparing with so...as (She is not so tall as me)'},
  {name: 'Anticipating with “going to”'},
  {name: 'Expressing Obligation (must, have to, should)'},
  {name: 'Making Suggestions (Let’s go, Why don’t we?)'},
  {name: 'Expressing Preferences (I prefer coffee over tea)'},
  {name: 'Giving Advice (You should...)'},
  {name: 'Making Requests (Can you, Could you, Would you?)'},
  {name: 'Polite Expressions (Excuse me, Please, Thank you)'},
  {name: 'Quantifying (a lot of, a few, some)'},
  {name: 'Relative Adverbs (where, why, when)'},
  {name: 'Questions with How (How long, How much, How many)'},
  {name: 'Giving Opinions (I think, I believe)'},
  {name: 'Offering Help (Can I help you?)'},
  {name: 'Talking about Habits (I always drink coffee in the morning)'},
  {name: 'Expressing Possibility (may, might, could)'},
  {name: 'Expressing Ability (can, be able to)'},
  {name: 'Expressing Permission (can, may, might)'},
  {name: 'Time Expressions (last year, tomorrow, next week)'},
  {name: 'Making Predictions (will, might, will probably)'},
];

export const conjugation = [
  { name: 'Present Simple Tense (I eat, you work)' },
  { name: 'Present Continuous Tense (I am eating, you are working)' },
  { name: 'Present Perfect Tense (I have eaten, you have worked)' },
  { name: 'Present Perfect Continuous Tense (I have been eating, you have been working)' },
  { name: 'Past Simple Tense (I ate, you worked)' },
  { name: 'Past Continuous Tense (I was eating, you were working)' },
  { name: 'Past Perfect Tense (I had eaten, you had worked)' },
  { name: 'Past Perfect Continuous Tense (I had been eating, you had been working)' },
  { name: 'Future Simple Tense (I will eat, you will work)' },
  { name: 'Future Continuous Tense (I will be eating, you will be working)' },
  { name: 'Future Perfect Tense (I will have eaten, you will have worked)' },
  { name: 'Future Perfect Continuous Tense (I will have been eating, you will have been working)' },
  { name: 'Conditional Simple Tense (I would eat, you would work)' },
  { name: 'Conditional Continuous Tense (I would be eating, you would be working)' },
  { name: 'Conditional Perfect Tense (I would have eaten, you would have worked)' },
  { name: 'Conditional Perfect Continuous Tense (I would have been eating, you would have been working)' },
  { name: 'Imperative Mood (Eat!, Work!)' },
  { name: 'Infinitive (To eat, to work)' },
  { name: 'Gerund (Eating, working)' },
  { name: 'Base Form (Eat, work)' },
  { name: 'First Person Singular (I eat, I work)' },
  { name: 'Second Person Singular (You eat, you work)' },
  { name: 'Third Person Singular (He/She eats, he/she works)' },
  { name: 'First Person Plural (We eat, we work)' },
  { name: 'Second Person Plural (You eat, you work)' },
  { name: 'Third Person Plural (They eat, they work)' },
  { name: 'Positive Sentence (I eat, you work)' },
  { name: 'Negative Sentence (I do not eat, you do not work)' },
  { name: 'Interrogative Sentence (Do I eat?, Do you work?)' },
  { name: 'Affirmative Sentence (I eat, you work)' },
  { name: 'Negative Interrogative Sentence (Don’t I eat?, Don’t you work?)' },
  { name: 'Modal Verbs (Can eat, must work)' },
  { name: 'Past Participle (Eaten, worked)' },
  { name: 'Present Participle (Eating, working)' },
  { name: 'Verb + Object (I eat an apple, you work hard)' },
  { name: 'Verb + Preposition (I am waiting for, you are talking to)' },
  { name: 'Phrasal Verbs (Give up, look after)' },
  { name: 'Causative Have (I have my car washed, you have your work done)' },
  { name: 'Adjective + Infinitive (Happy to eat, eager to work)' },
  { name: 'Adjective + Gerund (Tired of eating, bored of working)' },
  { name: 'Verb + Gerund (Enjoy eating, dislike working)' },
  { name: 'Verb + Infinitive (Want to eat, need to work)' },
  { name: 'Comparative Forms (More interesting, harder)' },
  { name: 'Superlative Forms (The most interesting, the hardest)' },
  { name: 'Future Perfect (I will have eaten, you will have worked)' },
  { name: 'Simple Past (I ate, you worked)' },
  { name: 'Future Simple (I will eat, you will work)' },
  { name: 'Verb + Adverb (He eats quickly, she works hard)' },
  { name: 'Past Simple Irregular Verbs (Go - went, See - saw)' },
  { name: 'Past Participle Irregular Verbs (Gone, Seen)' },
  { name: 'Present Perfect with Ever (I have ever eaten, you have ever worked)' },
  { name: 'Present Perfect with Never (I have never eaten, you have never worked)' },
  { name: 'Past Continuous with Always (I was always eating, you were always working)' },
  { name: 'Relative Clauses (The book I am reading, the work you are doing)' },
  { name: 'Exclamatory Sentences (What a beautiful meal!, How hard you work!)' },
  { name: 'Reported Speech (She says she eats, he says he works)' },
  { name: 'Direct Speech (I eat, you work)' },
  { name: 'Indirect Speech (He said that he ate, she said that she worked)' },
  { name: 'Subjunctive Mood (I wish I were eating, I suggest you work)' },
  { name: 'Conditional Sentences Type 1 (If I eat, I will work)' },
  { name: 'Conditional Sentences Type 2 (If I ate, I would work)' },
  { name: 'Conditional Sentences Type 3 (If I had eaten, I would have worked)' },
  { name: 'Present Continuous for Future (I am eating tomorrow, you are working next week)' },
  { name: 'Past Simple for Habit (I ate pizza every day, you worked in the office)' },
  { name: 'Future Simple for Predictions (I will eat later, you will work hard)' },
  { name: 'Future Continuous for Ongoing Future Action (I will be eating, you will be working)' },
  { name: 'Future Perfect for Future Completion (I will have eaten, you will have worked)' },
  { name: 'Future Simple for Spontaneous Decisions (I’ll eat now, I’ll work later)' },
  { name: 'Present Perfect with Just (I have just eaten, you have just worked)' },
  { name: 'Past Simple with Already (I already ate, you already worked)' },
  { name: 'Past Simple with Yet (I didn’t eat yet, you didn’t work yet)' },
  { name: 'Tag Questions (You eat, don’t you?, You work, don’t you?)' },
  { name: 'Question Words (Where do you eat?, When do you work?)' },
  { name: 'Conditional Statements with Unless (Unless I eat, I won’t work)' },
  { name: 'Passive Voice (The cake is eaten, the work is done)' },
  { name: 'Active Voice (I eat the cake, you do the work)' },
  { name: 'Modal Verbs for Permission (Can I eat?, May I work?)' },
  { name: 'Modal Verbs for Obligation (Must eat, should work)' },
  { name: 'Modal Verbs for Prohibition (Cannot eat, should not work)' },
  { name: 'Verb to Be + Adjective (I am hungry, you are tired)' },
  { name: 'Prepositions of Time (I eat at noon, you work in the morning)' },
  { name: 'Prepositions of Place (I eat at the table, you work in the office)' },
  { name: 'Prepositions of Movement (I go to work, you walk to the park)' },
  { name: 'Prepositions of Direction (I go into the kitchen, you walk out of the room)' },
  { name: 'Verb Tenses for Habitual Actions (I eat every day, you work every week)' },
  { name: 'Pronouns and Possessive Adjectives (I eat my food, you work your job)' },
  { name: 'Comparatives with Than (I eat more than you, you work harder than me)' },
  { name: 'Superlatives with The (I eat the best food, you work the hardest)' },
  { name: 'Direct Object (I eat an apple, you work on a project)' },
  { name: 'Indirect Object (I give him the apple, you give me the work)' },
  { name: 'Object Pronouns (I eat it, you work with him)' },
  { name: 'Reflexive Pronouns (I eat by myself, you work alone)' },
];

